name: Build & Release JavaScript Bindings

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install NAPI-RS CLI
        run: npm install
        working-directory: gp-bindings/js

      - name: Build native bindings
        run: napi build --release
        working-directory: gp-bindings/js

      - name: Upload binaries
        uses: softprops/action-gh-release@v2
        with:
          files: "npm/*/*.node"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
